#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Q W E R T Y U I O

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#282828"
bspc config focused_border_color "#BF0909"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

