#!/usr/bin/env bash

lines="-l 20"

selected="$(ps -a -u $USER | dmenu -p "Select process to kill :" $lines | awk '{print $1" "$4}')";

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | dmenu -p "$selected will be killed, are you sure?" )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        # echo $selpid
        kill -9 $selpid
    fi
fi

exit 0
